version: '3.8'

services:
  # ÉTAGE 1 : BDD (PostgreSQL)
  db:
    image: postgres:15
    container_name: pixmatcher_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend_network:
        aliases:
          - db

  # ÉTAGE 2 : Le Backend (FastAPI + IA)
  backend:
    build: ./backend
    container_name: pixmatcher_backend
    restart: always
    depends_on:
      - db
    volumes:
      - ./ressources:/app/ressources
    expose:
      - "8000"
    networks:
      - backend_network
      - frontend_network

  # ÉTAGE 3 : Le Frontend (Streamlit)
  frontend:
    build: ./frontend
    container_name: pixmatcher_frontend
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - backend
    env_file: .env
    volumes:
      - ./ressources:/app/ressources
    networks:
      - frontend_network

volumes:
  postgres_data:

networks:
  backend_network:
  frontend_network:
